import Head from 'next/head'
import { Navbar } from '../common/navbar/navbar.comp'
import { MainLayoutStyled } from './main-layout.styled'

export const MainLayout = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <MainLayoutStyled>
          <Navbar />
          <div className='content'>{children}</div>
        </MainLayoutStyled>
      </main>
    </>
  )
}
