import Head from 'next/head'
import { Navbar } from '../common/navbar/navbar.comp'

export const MainLayout = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Navbar />
        {children}
      </main>
    </>
  )
}
