version: '3.2'
services:
  zero:
    image: dgraph/dgraph:v21.03.2
    volumes:
      - ~/.dgraph/prefix/zero:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  alpha:
    image: dgraph/dgraph:v21.03.2
    volumes:
      - ~/.dgraph/prefix/alpha:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080
